[TDG-9] Tower stats
GianiStatie/tower-defense pull request #3
Opened 2023-09-30 21:52 UTC by Ratoone

2023-10-02 05:59 UTC, GianiStatie requested changes

2023-10-02 05:59 UTC, GianiStatie commented on src/UI/DebugUI.gd
> +		debug_state.text = "[center]%s[/center]" % owner.state_machine.state.name
oh wow ... didn't know you can do that

2023-10-02 05:59 UTC, GianiStatie commented on src/units/00_components/states/Reloading.gd
> +	var reload_seconds: float = 1 / owner.stats._rate_of_fire
[?] I imagined that the bigger the `_rate_of_fire` the more it shoots

2023-10-02 05:59 UTC, GianiStatie commented on src/units/00_components/states/IdleTower.gd
> +		get_parent().transition_to("Shooting", {"enemy": enemy})
[+] do `state_machine.transition_to()` rather than `get_parent()`. It looks better

2023-10-02 05:59 UTC, GianiStatie commented on src/units/00_components/states/Reloading.gd
> +	get_parent().transition_to("Idle")
[+] `state_machine.transition_to()`

2023-10-02 05:59 UTC, GianiStatie commented on src/units/00_components/states/Shooting.gd
> +		get_parent().transition_to("Reloading")
[+] `state_machine.transition_to()`

2023-10-02 05:59 UTC, GianiStatie commented on src/units/00_components/states/Shooting.gd
> +	owner.get_parent().add_child(bullet)
[+] `state_machine.transition_to()`. Sorry for the spamming, just want to make sure we don't miss one.

2023-10-02 05:59 UTC, GianiStatie commented on src/units/00_components/towers/TowerStats.gd
> +func _init(range: int, damage: int, rate_of_fire: float):
[?] what is the difference between `_init` and `_ready` ?

2023-10-02 13:46 UTC, Ratoone commented on src/UI/DebugUI.gd
> +		debug_state.text = "[center]%s[/center]" % owner.state_machine.state.name
me neither, you only need to make sure to enable BBCode in the label settings

2023-10-02 13:48 UTC, Ratoone commented on src/units/00_components/states/Reloading.gd
> +	var reload_seconds: float = 1 / owner.stats._rate_of_fire
rate of fire means shots per seconds. so if you increase it, the reload is faster

2023-10-02 13:49 UTC, Ratoone commented on src/units/00_components/states/IdleTower.gd
> +		get_parent().transition_to("Shooting", {"enemy": enemy})
oh, missed that one

2023-10-02 13:53 UTC, Ratoone commented on src/units/00_components/states/Shooting.gd
> +	owner.get_parent().add_child(bullet)
this is not the state machine, this is adding the bullet to the scene. i suppose it was a workaround for the bullet's position and target

2023-10-02 13:55 UTC, Ratoone commented on src/units/00_components/towers/TowerStats.gd
> +func _init(range: int, damage: int, rate_of_fire: float):
`_init` is called when you call `TowerStats.new()`. `_ready` is when the node is loaded into the scene. The tower stats acts like a struct that only holds the information. Later on, I want this to be used for deserializing the database of towers

2023-10-03 04:48 UTC, GianiStatie commented on src/units/00_components/states/Reloading.gd
> +	var reload_seconds: float = 1 / owner.stats._rate_of_fire
oh ... I'm stupid

2023-10-03 04:49 UTC, GianiStatie commented on src/units/00_components/states/Shooting.gd
> +	owner.get_parent().add_child(bullet)
you're right, I got carried away 😆

2023-10-03 04:58 UTC, GianiStatie approved these changes

2023-10-03 06:59 UTC, merged